name: talker_sqflite_logger_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  logging: ^1.2.0
  path: ^1.8.3
  sqflite: ^2.3.2
  sqflite_common: ^2.5.3
  talker: ^4.0.0
  talker_sqflite_logger:
    git:
      url: git@github.com:mateusfsilva/talker_sqflite_logger.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
